"""
pdf_exporter.py
---------------
Generates a premium PDF report for MuscleForge AI.
Supports the 3-option meal plan format (=== MEAL === / [A] [B] [C]).
"""

import io
import re
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import os

# ─── Brand colours ──────────────────────────────────────────────────────────
C_BG      = HexColor("#0f1117")
C_CARD    = HexColor("#1e2130")
C_PURPLE  = HexColor("#a855f7")
C_BLUE    = HexColor("#4f8ef7")
C_GREEN   = HexColor("#22c55e")
C_RED     = HexColor("#ef4444")
C_AMBER   = HexColor("#f59e0b")
C_WHITE   = HexColor("#ffffff")
C_MUTED   = HexColor("#aab2cc")
C_OPT_A   = HexColor("#4f8ef7")
C_OPT_B   = HexColor("#a855f7")
C_OPT_C   = HexColor("#22c55e")

OPTION_COLORS_PDF = {"A": C_OPT_A, "B": C_OPT_B, "C": C_OPT_C}

PAGE_W, PAGE_H = A4
MARGIN = 18 * mm

# ─── Section header translations ─────────────────────────────────────────────
_SECTION_LABELS = {
    "inbody_summary":   "InBody Summary",
    "daily_targets":    "Daily Nutrition Targets",
    "meal_plan":        "Meal Plan",
    "workout_plan":     "Workout Plan",
    "coach_notes":      "Coach Notes",
    "report_subtitle":  "Personal Fitness Report",
    "calories":         "Calories",
    "protein":          "Protein",
    "carbs":            "Carbs",
    "fat":              "Fat",
    "metric":           "Metric",
    "value":            "Value",
    "footer":           "Generated by MuscleForge AI — for informational purposes only. Consult a healthcare professional before starting any fitness program.",
}

_INBODY_LABELS = {
    "weight": "Weight", "height": "Height", "age": "Age",
    "biological_age": "Biological Age", "gender": "Gender",
    "body_fat_pct": "Body Fat %", "body_fat_mass": "Fat Mass",
    "muscle_mass": "Muscle Mass", "smm": "SMM",
    "visceral_fat": "Visceral Fat", "bmr": "BMR",
    "total_body_water": "Body Water",
}


# ─── Styles ──────────────────────────────────────────────────────────────────

# ─── Styles ──────────────────────────────────────────────────────────────────

def _styles():
    font_bold = "Helvetica-Bold"
    font_reg  = "Helvetica"
    align     = TA_LEFT

    return {
        "h1": ParagraphStyle("h1", fontName=font_bold, fontSize=22,
                             textColor=C_WHITE, alignment=TA_CENTER, spaceAfter=2),
        "sub": ParagraphStyle("sub", fontName=font_reg, fontSize=10,
                              textColor=C_MUTED, alignment=TA_CENTER, spaceAfter=4),
        "section": ParagraphStyle("section", fontName=font_bold, fontSize=13,
                                  textColor=C_PURPLE, spaceAfter=4, spaceBefore=10,
                                  alignment=align),
        "meal_title": ParagraphStyle("meal_title", fontName=font_bold, fontSize=11,
                                     textColor=C_WHITE, spaceAfter=2, spaceBefore=6,
                                     alignment=align),
        "opt_label": ParagraphStyle("opt_label", fontName=font_bold, fontSize=10,
                                    textColor=C_WHITE, spaceAfter=1, alignment=align),
        "opt_body": ParagraphStyle("opt_body", fontName=font_reg, fontSize=9,
                                   textColor=C_MUTED, spaceAfter=1, alignment=align),
        "opt_macro": ParagraphStyle("opt_macro", fontName=font_bold, fontSize=9,
                                    textColor=C_WHITE, spaceAfter=3, alignment=align),
        "normal": ParagraphStyle("normal", fontName=font_reg, fontSize=9,
                                 textColor=C_MUTED, spaceAfter=2, alignment=align),
        "bullet": ParagraphStyle("bullet", fontName=font_reg, fontSize=9,
                                 textColor=C_WHITE, spaceAfter=3, leftIndent=8,
                                 bulletIndent=0, alignment=align),
        "workout_day": ParagraphStyle("workout_day", fontName=font_bold, fontSize=10,
                                      textColor=C_BLUE, spaceAfter=2, spaceBefore=6,
                                      alignment=align),
        "workout_ex": ParagraphStyle("workout_ex", fontName=font_reg, fontSize=9,
                                     textColor=C_WHITE, spaceAfter=2, leftIndent=12,
                                     alignment=align),
    }


# ─── PDF colour patches (coloured background boxes) ──────────────────────────

def _color_table(items, bg, col_widths=None):
    """Wrap a list of Paragraphs in a coloured background table row."""
    usable_w = PAGE_W - 2 * MARGIN
    if col_widths is None:
        col_widths = [usable_w]
    tbl = Table([items], colWidths=col_widths)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return tbl


def _goal_banner(goal: str, styles: dict):
    goal_map = {
        "fat_loss":    ("FAT LOSS",    C_RED),
        "muscle_gain": ("MUSCLE GAIN", C_GREEN),
        "balanced":    ("BALANCED",    C_BLUE),
    }

    label_raw, colour = goal_map.get(goal, ("CUSTOM", C_PURPLE))
    p = Paragraph(f"<b>{label_raw}</b>", ParagraphStyle(
        "banner", fontName=styles["h1"].fontName, fontSize=20,
        textColor=C_WHITE, alignment=TA_CENTER))
    tbl = Table([[p]], colWidths=[PAGE_W - 2 * MARGIN])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colour),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("ROUNDEDCORNERS", [10, 10, 10, 10]),
    ]))
    return tbl


# ─── InBody summary table ─────────────────────────────────────────────────────

def _inbody_table(data: dict, style):
    rows = [
        [_SECTION_LABELS["metric"], _SECTION_LABELS["value"]],
        [_INBODY_LABELS["weight"],       f"{data.get('weight', '-')} kg"],
        [_INBODY_LABELS["height"],       f"{data.get('height', '-')} cm"],
        [_INBODY_LABELS["age"],          f"{data.get('age', '-')} yrs"],
        [_INBODY_LABELS["biological_age"], f"{data.get('biological_age', '-')} yrs"],
        [_INBODY_LABELS["gender"],       str(data.get('gender', '-')).capitalize()],
        [_INBODY_LABELS["body_fat_pct"], f"{data.get('body_fat_pct', '-')} %"],
        [_INBODY_LABELS["body_fat_mass"], f"{data.get('body_fat_mass', '-')} kg"],
        [_INBODY_LABELS["muscle_mass"],  f"{data.get('muscle_mass', '-')} kg"],
        [_INBODY_LABELS["smm"],          f"{data.get('smm', '-')} kg"],
        [_INBODY_LABELS["visceral_fat"], str(data.get('visceral_fat', '-'))],
        [_INBODY_LABELS["bmr"],          f"{data.get('bmr', '-')} kcal"],
        [_INBODY_LABELS["total_body_water"], f"{data.get('total_body_water', '-')} L"],
    ]
    usable_w = PAGE_W - 2 * MARGIN
    col_w = [usable_w * 0.5, usable_w * 0.5]
    tbl_data = []
    for i, row in enumerate(rows):
        r = []
        for cell in row:
            if isinstance(cell, str):
                st = style["opt_label"] if i == 0 else style["opt_body"]
                r.append(Paragraph(cell, st))
            else:
                r.append(cell)
        tbl_data.append(r)

    tbl = Table(tbl_data, colWidths=col_w)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), C_PURPLE),
        ("BACKGROUND", (0, 1), (-1, -1), C_CARD),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_CARD, HexColor("#252840")]),
        ("GRID", (0, 0), (-1, -1), 0.3, HexColor("#2e3250")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return tbl


# ─── Parse plan text ──────────────────────────────────────────────────────────

def _parse_plan(plan_text: str) -> dict:
    sections = {}
    current = None
    for raw in plan_text.strip().split("\n"):
        line = raw.strip()
        if not line:
            continue
        meal_m = re.match(r"===\s*(.+?)\s*===", line)
        if meal_m:
            current = meal_m.group(1).upper().strip()
            sections.setdefault(current, [])
            continue
        upper = line.upper().replace("*", "").replace("#", "").replace("-", "").strip(": ")
        if upper in ("WORKOUT PLAN", "COACH NOTES", "DAILY TARGET", "MEAL PLAN"):
            current = upper
            sections.setdefault(current, [])
            continue
        if current is not None:
            sections[current].append(line)
    return sections


def _parse_option(line: str) -> dict:
    parts = [p.strip() for p in line.split("|")]
    return {
        "name":        parts[0] if parts else line,
        "ingredients": parts[1] if len(parts) > 1 else "",
        "kcal":        parts[2] if len(parts) > 2 else "",
        "macros":      parts[3] if len(parts) > 3 else "",
    }


# ─── Build PDF ────────────────────────────────────────────────────────────────

def generate_pdf_report(
    weight, height, age, biological_age, gender,
    body_fat_pct, body_fat_mass, muscle_mass, smm,
    visceral_fat, bmr, total_body_water,
    goal, calories, protein, carbs, fat,
    plan_text: str
) -> bytes:

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        title="MuscleForge AI Report",
    )

    def draw_bg(canvas, doc):
        canvas.saveState()
        canvas.setFillColor(C_BG)
        canvas.rect(0, 0, PAGE_W, PAGE_H, fill=True, stroke=False)
        canvas.restoreState()

    S = _styles()
    story = []
    usable_w = PAGE_W - 2 * MARGIN

    # ── Cover ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("MuscleForge AI", S["h1"]))
    story.append(Paragraph(
        f"{_SECTION_LABELS['report_subtitle']} — {date.today().strftime('%d %B %Y')}",
        S["sub"]
    ))
    story.append(Spacer(1, 4 * mm))

    # ── Goal banner ──────────────────────────────────────────────────────────
    story.append(_goal_banner(goal, S))
    story.append(Spacer(1, 6 * mm))

    # ── InBody summary ───────────────────────────────────────────────────────
    story.append(Paragraph(_SECTION_LABELS["inbody_summary"], S["section"]))
    data_dict = {
        "weight": weight, "height": height, "age": age,
        "biological_age": biological_age, "gender": gender,
        "body_fat_pct": body_fat_pct, "body_fat_mass": body_fat_mass,
        "muscle_mass": muscle_mass, "smm": smm,
        "visceral_fat": visceral_fat, "bmr": bmr,
        "total_body_water": total_body_water,
    }
    story.append(_inbody_table(data_dict, S))
    story.append(Spacer(1, 5 * mm))

    # ── Daily targets ────────────────────────────────────────────────────────
    story.append(Paragraph(_SECTION_LABELS["daily_targets"], S["section"]))
    target_rows = [[
        Paragraph(f"<b>{_SECTION_LABELS['calories']}</b>", S["opt_label"]),
        Paragraph(f"<b>{_SECTION_LABELS['protein']}</b>",  S["opt_label"]),
        Paragraph(f"<b>{_SECTION_LABELS['carbs']}</b>",    S["opt_label"]),
        Paragraph(f"<b>{_SECTION_LABELS['fat']}</b>",      S["opt_label"]),
    ], [
        Paragraph(f"{calories} kcal", S["normal"]),
        Paragraph(f"{protein} g",     S["normal"]),
        Paragraph(f"{carbs} g",       S["normal"]),
        Paragraph(f"{fat} g",         S["normal"]),
    ]]
    col_w4 = [usable_w / 4] * 4
    t_targets = Table(target_rows, colWidths=col_w4)
    t_targets.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), C_BLUE),
        ("BACKGROUND", (0, 1), (-1, 1), C_CARD),
        ("GRID", (0, 0), (-1, -1), 0.3, HexColor("#2e3250")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t_targets)
    story.append(Spacer(1, 6 * mm))

    # ── Parse plan sections ───────────────────────────────────────────────────
    sections = _parse_plan(plan_text)

    # ── Meal Plan ─────────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=C_PURPLE, spaceAfter=4))
    story.append(Paragraph(_SECTION_LABELS["meal_plan"], S["section"]))

    meal_order = ["BREAKFAST", "SNACK 1", "LUNCH", "SNACK 2", "DINNER"]
    meal_labels = {
        "BREAKFAST": "Breakfast",
        "SNACK 1":   "Snack 1",
        "LUNCH":     "Lunch",
        "SNACK 2":   "Snack 2",
        "DINNER":    "Dinner",
    }

    for meal_name in meal_order:
        if meal_name not in sections:
            continue
        meal_lines = sections[meal_name]

        meal_label = meal_labels.get(meal_name, meal_name.title())

        tbl_header = _color_table(
            [Paragraph(f"<b>{meal_label}</b>", S["meal_title"])],
            HexColor("#252840"),
        )
        story.append(tbl_header)

        # Parse options
        options = {}
        for ml in meal_lines:
            opt_m = re.match(r"\[([ABC])\]\s*(.+)", ml)
            if opt_m:
                letter = opt_m.group(1)
                options[letter] = _parse_option(opt_m.group(2))

        if options:
            opt_cells = []
            opt_col_w = [usable_w / len(options)] * len(options)
            for letter in sorted(options.keys()):
                opt = options[letter]
                col_c = OPTION_COLORS_PDF.get(letter, C_WHITE)
                name_text  = opt["name"]
                ingr_text  = opt["ingredients"]
                kcal_text  = str(opt["kcal"])
                macro_text = str(opt["macros"])
                cell_content = [
                    Paragraph(f"<b>Option {letter}</b>", ParagraphStyle(
                        f"ol{letter}", fontName=S["opt_label"].fontName, fontSize=9,
                        textColor=col_c)),
                    Paragraph(f"<b>{name_text}</b>", ParagraphStyle(
                        f"on{letter}", fontName=S["opt_label"].fontName, fontSize=9,
                        textColor=C_WHITE, alignment=S["opt_label"].alignment)),
                    Paragraph(ingr_text, S["opt_body"]),
                    Spacer(1, 2),
                    Paragraph(kcal_text, ParagraphStyle(
                        f"ok{letter}", fontName=S["opt_label"].fontName, fontSize=9,
                        textColor=col_c)),
                    Paragraph(macro_text, S["opt_body"]),
                ]
                opt_cells.append(cell_content)

            opt_tbl = Table([opt_cells], colWidths=opt_col_w)
            opt_tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), C_CARD),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#2e3250")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(opt_tbl)
        else:
            for ml in meal_lines:
                story.append(Paragraph(ml, S["normal"]))

        story.append(Spacer(1, 3 * mm))

    # ── Workout Plan ──────────────────────────────────────────────────────────
    if "WORKOUT PLAN" in sections:
        story.append(HRFlowable(width="100%", thickness=1, color=C_BLUE, spaceAfter=4))
        story.append(Paragraph(_SECTION_LABELS["workout_plan"], S["section"]))
        workout_lines = sections["WORKOUT PLAN"]
        for wl in workout_lines:
            if not wl:
                continue
            stripped = wl.lstrip("-–—•* \t")
            is_bullet = len(wl) > 0 and wl[0] in "-–—•*"
            if is_bullet:
                story.append(Paragraph(f"&nbsp;&nbsp;&nbsp;• {stripped}", S["workout_ex"]))
            else:
                story.append(Spacer(1, 3 * mm))
                story.append(Paragraph(wl, S["workout_day"]))

    # ── Coach Notes ───────────────────────────────────────────────────────────
    if "COACH NOTES" in sections:
        story.append(HRFlowable(width="100%", thickness=1, color=C_AMBER, spaceAfter=4))
        story.append(Paragraph(_SECTION_LABELS["coach_notes"], S["section"]))
        for note in sections["COACH NOTES"]:
            note = note.lstrip("-•* ")
            if note:
                story.append(Paragraph(f"• {note}", S["bullet"]))

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 8 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_MUTED))
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(
        _SECTION_LABELS["footer"],
        ParagraphStyle("footer", fontName=S["normal"].fontName, fontSize=7,
                       textColor=C_MUTED, alignment=TA_CENTER)
    ))

    doc.build(story, onFirstPage=draw_bg, onLaterPages=draw_bg)
    return buf.getvalue()


# ─── Self-test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    sample_plan = """DAILY TARGET
2200 kcal | P: 160g | C: 240g | F: 70g

MEAL PLAN

=== BREAKFAST ===
[A] Oatmeal Power | 250g oats, 2 eggs, 1 banana | 420 kcal | P:24g C:60g F:12g
[B] Egg Scramble | 3 eggs, 100g whole wheat bread, 10ml olive oil | 380 kcal | P:22g C:38g F:18g
[C] Yogurt Bowl | 200g greek yogurt, 1 banana, 30g almonds | 350 kcal | P:20g C:35g F:15g

=== SNACK 1 ===
[A] Apple & Almonds | 1 apple, 30g almonds | 200 kcal | P:5g C:22g F:11g
[B] Greek Yogurt | 150g greek yogurt, 1 tbsp peanut butter | 180 kcal | P:14g C:10g F:8g
[C] Tuna Crackers | 1 can tuna, 5 crackers | 180 kcal | P:20g C:12g F:4g

=== LUNCH ===
[A] Chicken & Rice | 150g chicken breast, 200g rice, broccoli | 540 kcal | P:45g C:60g F:10g
[B] Tuna Pasta | 120g tuna, 150g pasta, spinach | 490 kcal | P:38g C:55g F:8g
[C] Beef & Potato | 120g lean beef, 200g sweet potato | 510 kcal | P:40g C:50g F:12g

=== SNACK 2 ===
[A] Banana & PB | 1 banana, 1 tbsp peanut butter | 220 kcal | P:6g C:30g F:9g
[B] Cheese & Bread | 50g cheese, 2 slices whole wheat | 210 kcal | P:12g C:20g F:10g
[C] Milk & Oats | 200ml milk, 40g oats | 200 kcal | P:10g C:30g F:5g

=== DINNER ===
[A] بيك سمك | 150g سمك مشوي, 200g بطاطا حلوة, سبانخ | 480 kcal | P:40g C:35g F:18g
[B] دجاج وباستا | 150g صدر دجاج, خضار مشكل | 420 kcal | P:42g C:18g F:14g
[C] Lentil Bowl | 200g lentils, 100g rice | 400 kcal | P:22g C:60g F:4g

WORKOUT PLAN
Day 1 — Chest and Triceps
- Bench Press — 4 x 8
- Incline Dumbbell Press — 3 x 10
- Tricep Pushdown — 3 x 12

Day 2 — Back and Biceps
- Pull-ups — 3 x 8
- Barbell Row — 4 x 8
- Bicep Curl — 3 x 12

COACH NOTES
- اشرب 3 لترات من الماء يومياً.
- نم 7-8 ساعات للتعافي.
- Track your meals to stay on target.
"""

    pdf = generate_pdf_report(
        weight=80, height=175, age=25, biological_age=28,
        gender="Male", body_fat_pct=18.0, body_fat_mass=14.4,
        muscle_mass=60.0, smm=32.0, visceral_fat=8, bmr=1750,
        total_body_water=45.0, goal="balanced",
        calories=2200, protein=160, carbs=240, fat=70,
        plan_text=sample_plan
    )
    fname = "test_report.pdf"
    with open(fname, "wb") as f:
        f.write(pdf)
    print(f"[OK] PDF written: {fname} ({len(pdf):,} bytes)")
